apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test-namespace
resources:
  - ../local/namespace.yaml
  - ../../apps/nginx-example/environments/local

commonLabels:
  environment: loc
