apiVersion: apps/v1
kind: Deployment
metadata:
  name: myimage-deployment
  labels:
    app: myimage
spec:
  selector:
    matchLabels:
      app: myimage
  template:
    metadata:
      labels:
        app: myimage
    spec:
      containers:
        - name: myimage
          image: docker.io/psoftg/myimage:1.0.0 # {"$imagepolicy": "flux-system:myimage"}
          ports:
            - containerPort: 80